### ISSUE TITLE
issue while importing scripts.config

### ISSUE THREAD

**Issue by aniketzz** [asanakoy/deeppose_tf#18]
after running the command **python datasets/mpii_dataset.py** I am getting the error as no module named scripts.config.
Here is what I got when i run the command. 
**aniket@LAPTOP-DAK58UAQ:~/deeppose_tf$ python datasets/mpii_dataset.py
Traceback (most recent call last):
  File "datasets/mpii_dataset.py", line 14, in <module>
    from scripts.config import *
ImportError: No module named scripts.config**

**Comment by asanakoy** [comment]
add path to `deeppose_tf` folder into the `PYTHONPATH` environmental variable

**Comment by aniketzz** [comment]
i tried adding the deeppose_tf folder into the PYTHONPATH environment variable but i even though i am getting the same error. may i know how are you suggesting to add to the PUTHONPATH. I tried using windows-linux bash and also on windows as well...  I am also getting an error "Export Command not found" when i am using windows bash to add the path and with the windows terminal i am still getting the same issue as mentioned in earlier comments.

**Comment by aniketzz** [comment]
i figured it out.. thanks.
