### ISSUE TITLE
 bvlc_alexnet.tf: File cannot found

### ISSUE THREAD

**Issue by shiangyoung** [asanakoy/deeppose_tf#3]
Anyone could share the bvlc_alexnet.tf file to me?
Thank you in advance.

**Comment by asanakoy** [comment]
Read the description first. 
https://hcicloud.iwr.uni-heidelberg.de/index.php/s/QBSJhaymOLGxz6M

**Comment by asanakoy** [comment]
https://hcicloud.iwr.uni-heidelberg.de/index.php/s/sNklPpCiqOYOCAz

**Comment by asanakoy** [comment]
Fixed the link in the readme.

**Comment by shiangyoung** [comment]
thank you very much

**Comment by Gannyn** [comment]
the link https://hcicloud.iwr.uni-heidelberg.de/index.php/s/sNklPpCiqOYOCAz cannot be  accessed.
Anyone could share the bvlc_alexnet.tf file to me?
Thank you in advance.
