### ISSUE TITLE
How do I use my own images for prediction?

### ISSUE THREAD

**Issue by shiangyoung** [asanakoy/deeppose_tf#4]
Hello, 

I was wondering if I could use my own images for prediction. I tried to run the test_snapshot.py. I'm looking for a result similar to #2 where the images are visualized. Could someone help me out?

Thank you.

**Comment by asanakoy** [comment]
@shiangyoung just get the predictions out of the network and write a script for visualization.
You will ned to save `predicted_joints` . Yo can check  [ `evaluate_pcp()`](https://github.com/asanakoy/deeppose_tf/blob/master/scripts/regressionnet.py#L293) to see how predicted joints are calculated.

**Comment by shiangyoung** [comment]
Hi @asanakoy,

We are currently running some tests however the predicted joints that we receive back is inaccurate. Could I ask if we are required to annotate the images before using them for testing?

Thank you for your earlier feedback.

**Comment by asanakoy** [comment]
@shiangyoung as I understood you right, for testing you need annotations only to get a PCP/PCKh score.
You need to train until the net converges.

**Comment by shiangyoung** [comment]
Hi @asanakoy,

Yup, we are currently training and it has reached around 220k steps. From what I understand, it would then be possible to use our own image for prediction without any prior annotations? We are actually aiming to get a visualization of the prediction using our own image. 

Thanks.
