### ISSUE TITLE
260k interations, mPCP on LSP is close to 0.42 with Imagenet initialization

### ISSUE THREAD

**Issue by jjzhang10** [asanakoy/deeppose_tf#7]
I train the LSP dataset with imagenet initialization. It has been 260k iterations, the train/pose_error is around[0.02 0.03]. The mPCP score (0.42) is still far from the result listed in the table. It does increase, but pretty slowly.

Does it mean it cannot converge for this time? I need restart the training?  Thanks.
![wechat image_20170707094329](https://user-images.githubusercontent.com/11369834/27962869-cb0cd9a0-62f8-11e7-956d-e751b8361ddb.jpg)

**Comment by asanakoy** [comment]
Looks like you initialized it randomly. On my experience  Radom initialization achieves PCP score ~0.42

**Comment by jjzhang10** [comment]
@asanakoy  I forget to add the parameter "fix_conv_lr 10000". Training the conv and fc weights together at the very beginning may hurt the performance for the fine-tuning on imagenet.
Now here is the result:
![qq 20170708182817](https://user-images.githubusercontent.com/11369834/27989898-4a662fd6-640b-11e7-9ae9-d19b871a21df.png)

The train/pose_loss is already lower to 0.03 (you mentioned in the previous post) after 140k iterations, but the test/mPCP is around 0.47. Will wait and see whether it will achieve 0.55
By the way, will the program converge every time?

**Comment by asanakoy** [comment]
You need to train longer. Should converge
