### ISSUE TITLE
Unable to download lsp dataset

### ISSUE THREAD

**Issue by mengnan1994** [asanakoy/deeppose_tf#9]
--2017-10-14 17:34:56--  https://engineering.leeds.ac.uk/info/20132/school_of_computing
Resolving engineering.leeds.ac.uk (engineering.leeds.ac.uk)... 129.11.26.47
Connecting to engineering.leeds.ac.uk (engineering.leeds.ac.uk)|129.11.26.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘lsp_dataset_original.zip’

lsp_dataset_original.zip      [    <=>                            ]  76.47K  19.8KB/s    in 3.9s    

2017-10-14 17:35:08 (19.8 KB/s) - ‘lsp_dataset_original.zip’ saved [78308]

Archive:  lsp_dataset_original.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of lsp_dataset_original.zip or
        lsp_dataset_original.zip.zip, and cannot find lsp_dataset_original.zip.ZIP, period.
mkdir: cannot create directory ‘lsp’: File exists
mv: cannot stat 'images': No such file or directory
mv: cannot stat 'joints.mat': No such file or directory
mv: cannot stat 'README.txt': No such file or directory
--2017-10-14 17:35:09--  http://www.comp.leeds.ac.uk/mat4saj/lspet_dataset.zip
Resolving www.comp.leeds.ac.uk (www.comp.leeds.ac.uk)... 129.11.133.104
Connecting to www.comp.leeds.ac.uk (www.comp.leeds.ac.uk)|129.11.133.104|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://engineering.leeds.ac.uk/info/20132/school_of_computing [following]
--2017-10-14 17:35:09--  https://engineering.leeds.ac.uk/info/20132/school_of_computing
Resolving engineering.leeds.ac.uk (engineering.leeds.ac.uk)... 129.11.26.47
Connecting to engineering.leeds.ac.uk (engineering.leeds.ac.uk)|129.11.26.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘lspet_dataset.zip’

lspet_dataset.zip             [   <=>                             ]  76.47K   169KB/s    in 0.5s    

2017-10-14 17:35:11 (169 KB/s) - ‘lspet_dataset.zip’ saved [78308]

Archive:  lspet_dataset.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of lspet_dataset.zip or
        lspet_dataset.zip.zip, and cannot find lspet_dataset.zip.ZIP, period.
mkdir: cannot create directory ‘lsp_ext’: File exists
mv: cannot stat 'images': No such file or directory
mv: cannot stat 'joints.mat': No such file or directory
mv: cannot stat 'README.txt': No such file or directory

**Comment by asanakoy** [comment]
They changed the URLs to the archives. Now fixed.
